wandb_version: 1

batch_size:
  desc: null
  value: 256
num_episodes:
  desc: null
  value: 10000
num_iterations:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
epsilon_decay:
  desc: null
  value: 0.995
gamma:
  desc: null
  value: 0.95
epsilon_min:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722236925
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
